### ISSUE TITLE
How to load HQ sounds (SoundBulb)

### ISSUE THREAD

**Issue by Sol1vaN** [BodbDearg/PsyDoom#112]
I want to add HQ sounds.
An incredible MOD called DOOM CE have this resources.
https://www.moddb.com/mods/doom-ce/addons/doom-64-sound-bulb-high-quality-sounds

The format are in .WAD extension
I've readed the psydoom manual and this says:
_user specifies which mod directory to use via the -datadir <MY_DIRECTORY_PATH>_
or vía GUI windows in mod directory field:
![image](https://github.com/BodbDearg/PsyDoom/assets/33560454/8c2d9e62-8216-4535-8536-2a931853ca6a)

also i've readed that _files found in this folder will override existing_
i've extracted all the files with slade:
![image](https://github.com/BodbDearg/PsyDoom/assets/33560454/455af303-ef50-47c2-8856-80a486c3b450)

but nothing happens:
![image](https://github.com/BodbDearg/PsyDoom/assets/33560454/4f0a7e9a-be55-4a25-9246-1fe0cd46da2d)

looking closely, the manual only indicates about files (map WADS) _can only be used to contain data and scipts for a single level; all other contents of these WAD files will be ignored._

that's means that SFX files will be ignored too?
or i'm understanding something wrong?
https://github.com/BodbDearg/PsyDoom/blob/master/docs/PsyDoom%20Modding%20Overview.md

i hope PsyDoom can be played with HQ sound, this backport is impressive.
cheers.

**Comment by BodbDearg** [comment]
Adding new sounds is not a trivial task, unfortunately. The samples have to be in the same ADPCM format used by the PSX SPU (PsyDoom's audio tools can be used to encode to that format) and each sound is not just a raw audio clip, it's actually small MIDI-like sequence with notes and control data such as pitch shift and volume. In order to add new sounds you need to build a new .LCD archive containing the audio data for the sample itself (and all other samples- it is an archive file) and also compile a new .WMD file containing the MIDI sequence for the sound. I created scripts to do that for the new sounds in the GEC Master Edition here:
https://github.com/BodbDearg/PsyDoom/blob/2c50690b6e0ae26cbb83ad9039d24748f76275f8/extras/psydoom_mapping/Build%20ALLMAPS.LCD/build.py
https://github.com/BodbDearg/PsyDoom/blob/2c50690b6e0ae26cbb83ad9039d24748f76275f8/extras/psydoom_mapping/Build%20DOOMSND.WMD/build.py

**Comment by Sol1vaN** [comment]
sadly, i have no idea how to do all this.
i'll try, if i can.
