### ISSUE TITLE
Can't bind the gamepad start button for menu

### ISSUE THREAD

**Issue by Tasosgemah** [BodbDearg/PsyDoom#17]
the start button is "pause" by default. But i want to change it so the menu appears. This way i can just use the gamepad and not need a keyboard (for couch gaming) but i can't figure out how to do it.

**Comment by BodbDearg** [comment]
Hi @Tasosgemah see the answer to this question here:
https://www.doomworld.com/forum/topic/111024-psydoom-080-psx-doom-port-reverse-engineered-for-pc/?page=21&tab=comments#comment-2352467

Opening up the options menu is a combination of 'start' (pause) + 'select' (menu back) - same as the original PSX version. You don't need a keyboard to navigate around once you are inside the app.

BTW I have the Escape key on the keyboard bound to _both_ these actions by default as a convenience (so it goes straight to the main menu), you could do a similar thing with a gamepad also. I like to keep the actions separate by default for the gamepad however in order to make the navigation feel closer to the original game.
