### ISSUE TITLE
Original PSX Menu Emulation (Configuration menu)

### ISSUE THREAD

**Issue by OpenRift412** [BodbDearg/PsyDoom#19]
It would be nice to have an option for PsyDoom to emulate the original Options menu layout, allowing players to set up their controls in-game when using a controller (maybe add the ability to set keyboard binds in this menu as well?).

**Comment by BodbDearg** [comment]
Hey @OpenRift412 thanks for the suggestion. The original controls menu was removed because it no longer makes sense for PC players. Most are not playing with that anything that resembles the PSX controller and the binding options that this menu offered were very limited.

I've considered an alternate menu for all of the new bindings stuff but unfortunately the very low screen resolution that must be supported (for the classic renderer) and corresponding lack of screen real estate for listing all of the bindings and buttons make this not really feasible.

The best option for now is to use the flexible external configuration files with the option later of maybe doing some sort of configuration/launcher program to make setting things up easier on the user.

**Comment by OpenRift412** [comment]
> Hey @OpenRift412 thanks for the suggestion. The original controls menu was removed because it no longer makes sense for PC players. Most are not playing with that anything that resembles the PSX controller and the binding options that this menu offered were very limited.
> 
> I've considered an alternate menu for all of the new bindings stuff but unfortunately the very low screen resolution that must be supported (for the classic renderer) and corresponding lack of screen real estate for listing all of the bindings and buttons make this not really feasible.
> 
> The best option for now is to use the flexible external configuration files with the option later of maybe doing some sort of configuration/launcher program to make setting things up easier on the user.

Perhaps it could be a scrollable menu for the controls page, akin to Doom 64's original binds menu?

**Comment by BodbDearg** [comment]
It could be scrollable, but that only really works up to a point and becomes a pain after that if the list is too long. There is also the issue of horizontal space too, which is probably the larger problem. Due to the low resolution it would be hard to display a list of key-names for some bindings and keep it all on-screen.
