### ISSUE TITLE
View bobbing questions

### ISSUE THREAD

**Issue by j0r9** [BodbDearg/PsyDoom#2]
Hello,

first of all, thanks for this wonderful project. I've always been a fan of the PlayStation port of Doom and always wondered if someone was gonna port it to the PC without the need of an emulator.

I noticed in the original PlayStation version, the view bobbing behaves differently than it does in PsyDoom.

If I understand your notes correctly, if the original version would run at 15fps, the view bobbing would be much stronger than in an area where the fps is 30?
And the setting "FixViewBobStrength = 1" basically enforced the view bobbing to a fixed strength, which is set in the multiplier parameter? If the multiplier is set to 1.0, are you sure that this matches the maximum view bobbing of the original?

And one other question I have about the view bobbing: When the gun is swaying from left to right, the amount of frames this takes seems limited compared to the original PC release and so this animation is not as smooth. Is there any way this could be improved upon perhaps?

Regards

**Comment by BodbDearg** [comment]
Hi @j0r9 thank you for checking out the project.

Yes, you are correct. PSX Doom has (unfortunately) two tick lengths, one where the game simulates 1/15 seconds (what I call a 15 Hz tick) and one where it simulates 1/30 seconds (30 Hz tick). Depending on the performance of the current scene or even whatever way the timings work out between alternate frames the game can flip-flop between these two timestep lengths.

While some bits of the code take into account the length of time being simulated there are many parts of the code that don't, which causes very inconsistent behavior with the game's physics. Gravity for instance was not adjusted for the timestep duration, resulting in far too strong gravity when the game is running at high FPS. This video shows the difference between gravity at 15 Hz and gravity at 30 Hz:
[https://www.youtube.com/watch?v=7RBycvyZf3I](https://www.youtube.com/watch?v=7RBycvyZf3I)
 
The situation with view bobbing was somewhat similar - again not being adjusted for the length of time being simulated.

Since the game was more often than not at the 15 FPS mark (or close to it), the view bob strength fix adjusts PsyDoom's view bobbing so it behaves more like the original 15 Hz bobbing, since PsyDoom should pretty much always be locked at 30 Hz. I can never say it will be exactly the same as the original PSX bobbing however since that was not actually a fixed quantity and would change in strength from frame to frame depending on what the precise performance characteristics of the original hardware - something that PsyDoom cannot replicate given that it is now native to PC and not emulated.

I've run PsyDoom and emulated PSX Doom side by side however and the bobbing feels close in both instances and it's definitely much closer than the 0.5.x or earlier versions of PsyDoom. The PSX version sometimes feels like it has less bobbing (or it is less evident) due to the lower frame rate but it's definitely there if you look closely enough.

To answer some more of your questions:

> And the setting "FixViewBobStrength = 1" basically enforced the view bobbing to a fixed strength

The strength is not fixed, it's still based on how fast the player is moving like the original bobbing. So it's much stronger when you run and so on... The fix acts like a scaling adjustment of the original bobbing value.

> If the multiplier is set to 1.0, are you sure that this matches the maximum view bobbing of the original?

The multiplier just scales the resulting final amount of bobbing that is calculated, regardless of whether the fix to view bobbing is applied or not. It's provided so people can dial it down the effect if they find it distasteful. So, if you set the multiplier to 0.5 then the bobbing strength is halved for instance.

> And one other question I have about the view bobbing: When the gun is swaying from left to right, the number of frames this takes seems limited compared to the original PC release and so this animation is not as smooth. Is there any way this could be improved upon perhaps?

There are no animation frames involved since it's just translating the gun around, but you raise a good point. Presently I do not do any sort of interpolation for gun sway which may make its motion look a little jerky compared to the rest of PsyDoom's interpolated movement which can run at 60 Hz or 120 Hz or whatever your monitor can handle... I'll make a note of it to add this feature at some point - it should be even more useful once a higher resolution renderer is implemented.

**Comment by BodbDearg** [comment]
Added weapon sway interpolation to the TODO list in d02c42163ba10dc131eb0104ae64728d9df72b49. Closing ticket.
