### ISSUE TITLE
Feature request: Swap key for shotgun/super shotgun

### ISSUE THREAD

**Issue by thekovic** [BodbDearg/PsyDoom#23]
This optional key would allow the player to swap between SSG and normal shotgun with a single key - allowing the user to switch weapons the exact same way as in PC Doom. Presently, the weapon slots mirror the PSX Doom HUD layout which means that the SSG slot into number 4 and everything else moves up one slot which goes against 20 years of my muscle memory.

**Comment by BodbDearg** [comment]
Thanks for the suggestion! Had a think about this and came to the conclusion that it might cause some awkwardness with the UI because it would cause a mismatch between the numbers you press and those displayed on the HUD. One of the weapon slots could be removed to fix this but then it would leave a hole in part of the UI, which would look odd. Configuring this would also be somewhat awkward since you'd need to rebind most of the weapon numbers and also enable a separate option for a PC style weapon HUD layout.

Overall I feel like this perhaps doesn't belong in a port of the PSX game. Plus having a dedicated key for SSG and regular shotgun is actually a bonus and a much better way of directly choosing weapons, once you get used to it.

If you find it a little weird as an alternative I would suggest using the mouse wheel to cycle through the weapons, like how PSX players did on the gamepad. That's pretty quick and easy to do and normally how I play the game personally.

**Comment by yum13241** [comment]
About the "blank weapon slot" thing, that happens in regular PSX Doom. Just play the Ultimate Doom part of the game and forget that "The Marshes" exists, since that's the only place where you can get the SSG in UDoom.

> If you find it a little weird as an alternative I would suggest using the mouse wheel to cycle through the weapons, like how PSX players did on the gamepad. That's pretty quick and easy to do and normally how I play the game personally.

I do that, but the number keys guarantee you won't overshoot your weapon.  My muscle memory really does not like this change.
