### ISSUE TITLE
Negative Frags Display

### ISSUE THREAD

**Issue by fenderc01** [BodbDearg/PsyDoom#31]
In deathwatch, negative frags are displayed with a leading zero instead of a negative sign. Maybe this is intentional due to the limited characters available.

**Comment by BodbDearg** [comment]
Nice catch! Looks like it is an issue introduced by PsyDoom specifically, the problem does not happen in the original game.

The problem was introduced during the conversion of 'I_DrawNumber' from ASM to C++ by this commit: https://github.com/BodbDearg/PsyDoom/commit/ed107f3e9a70c96f3181a143b5c4808ad8a680f2

**Comment by BodbDearg** [comment]
This bug should be fixed as of 1.0.0 - closing ticket.
