### ISSUE TITLE
Co-Op: Enemies Sometimes Don't Start Moving Right Away When They See the Player

### ISSUE THREAD

**Issue by fenderc01** [BodbDearg/PsyDoom#36]
Enemies sometimes don’t see the player until you are closer (Example: Final Doom MAP01, long hallway with demons)

**Comment by fenderc01** [comment]
Upon second look, it seems like there is a delay for some enemies, from when the enemy sees you to when they actually start moving, compared to when you play single player.

In my example above, this is more apparent on the easiest difficulty. I should clarify, I am talking about the hallway on the west side of the map.

**Comment by BodbDearg** [comment]
Investigated and it looks like it's an artifact of how the game works in multiplayer. Enemies are able to do one sight check per tick and they randomly pick which player to check against. If you're lucky you might skip a few frames before they try and see your player - hence the delay. It also doesn't help that the tick rate is 15 Hz versus 35 Hz on PC, so those missed ticks are much longer...

I'm sort of reluctant to change this though (the change would also be complex) since it might alter the feel of co-op too much from the original experience. Leaving as-is for now.
