### ISSUE TITLE
Feature Request: Per-Game Saves/Saves in Same Folder As Exe

### ISSUE THREAD

**Issue by fenderc01** [BodbDearg/PsyDoom#42]
I have a couple suggestions for save files:

1. It would be nice if we could have saves on a per-game basis instead of having global saves. (Quick-Doom.sav, Quick-FinalDoom.sav, etc...)
2. It would also be nice if saves could be in the local folder, for portability purposes, like the config files currently can be. This could be configured in one of the ini files.

**Comment by BodbDearg** [comment]
Thanks for the suggestions @fenderc01. For #1 I think this would be a good idea to implement.

Concerning #2 I actually sort of regret allowing config files to reside locally in the same folder as the game .exe since it can create confusion as to where the game is sourcing the settings from. It would have been more simple and cleaner to keep everything in the PsyDoom 'AppData' folder (on Windows) rather than allowing 2 different config locations. I'll keep the local config feature alive for backwards compatibility but don't want to extend it any further to cover save files. 

PsyDoom in future will feature a launcher which will make editing and changing configs much easier, as well as picking which game CD to launch. It will also allow easy access to the 'AppData' folder for backup purposes via a built in shortcut. These two features combined should largely eliminate the need for local configs and save files.

**Comment by fenderc01** [comment]
I understand your stance on keeping everything in one spot under the user profile. I guess I'm an edge, case since I keep PsyDoom on my OneDrive, so I can play anywhere and my settings and saves travel with me.

**Comment by BodbDearg** [comment]
One other comment: if trying to use save files with cloud storage then perhaps you could use a symlink to make the PsyDoom config folder link to a folder on your cloud drive? I suspect that could work well and wouldn't require any changes to the game.
