### ISSUE TITLE
Feature Request: Block hitscan linedef flag

### ISSUE THREAD

**Issue by Dragonsbrethren** [BodbDearg/PsyDoom#47]
A request for level designers: A flag that makes a linedef act solid to hitscan attacks, like the one that already exists for projectiles. This would allow, for example, a window that blocks gunfire and projectiles from passing through, but still allows monsters to see the player and react. It would also have really interesting potential when paired with Arch-Viles.

Currently it's possible to fake this with the ghost platform flag, but it requires dummy sectors placed around the lines we want to block hitscans with.

**Comment by BodbDearg** [comment]
It's a good idea but sadly not possible due to the limitations of the PSX map format. Linedef flags are only stored in 16-bits in the map format, thus the engine can only use a maximum of 16 flags. PsyDoom has currently exhausted all of them, here's the list: 

https://github.com/BodbDearg/PsyDoom/blob/2cb1613ac754ec93b06294d7bf93977bb0457049/game/Doom/Game/doomdata.h#L27
