### ISSUE TITLE
Feature Request: Command Line Options for Doom Builder

### ISSUE THREAD

**Issue by fenderc01** [BodbDearg/PsyDoom#52]
It would be nice to have command line options to use when creating custom maps in Doom Builder, such as:
- WAD File
- Warp
- Skill

This would allow you to use the "Test Map - F9" feature in Doom Builder. I realize there is an "in-place map reload" feature, but it would allow you to get right to the map without going through the intro, title screen, main menu, and warp cheat.

As a side effect of adding these, you could also choose these options in the launcher.

**Comment by BodbDearg** [comment]
As of 1.0.0 the '-warp' and '-skill' command line arguments have been added to PsyDoom.

PsyDoom mods are supplied in terms of a directory (not a single wad file like PC) since each map in the PSX engine is it's own individual WAD file. Hence you must use the '-datadir' command instead of '-file'.

This wad directory concept of course doesn't really exist in Doom Builder so it's not possible to have it fill in the paths automatically when launching the executable. This means that you will have to manually add that information in for your launch configuration, unfortunately.

Closing the ticket since it should now be possible to launch from DB in the way you described, albeit with some slightly awkward setup.
