### ISSUE TITLE
Include the README and LICENSE in releases?

### ISSUE THREAD

**Issue by aybe** [BodbDearg/PsyDoom#56]
Currently there's only the executable in the archive.

It would be nice if you'd include useful information in the archive as well beside the executable itself.

Also, there should be a link to the repository itself in the README.

**Comment by BodbDearg** [comment]
Yeah that's intentional. On all 3 supported platforms PsyDoom ships as just a single executable or application which makes it almost impossible to mess up an installation and keeps everything as simple as possible.

If license or readme info is desired then the place to look for these artifacts is on the GitHub site - from same place where PsyDoom was obtained. I could include them in the distribution but then this then limits the ability to update these documents and make corrections without shipping a new release. For that reason I am against bundling them with the application.

**Comment by aybe** [comment]
Alright, makes sense.
