### ISSUE TITLE
Feature Request: Ultra Violence+ & Multiplayer

### ISSUE THREAD

**Issue by HardwareBreaker** [BodbDearg/PsyDoom#58]
Now that Ultra Violence+ has become a standard difficulty in the official source port and
other source ports it would be nice to see it incorporated as an option in PsyDoom.

[Ultra Violence+]

 UV+ brings about the following changes to gameplay:

- Ultra-Violence skill level
- Monsters are now fast
- All multiplayer objects are now spawned with the level

[Multiplayer] via Internet.

I have a small amount of experience in networking but probably not a great enough understanding to warrant
creating a bad fork of PsyDoom. Are there plans to make PsyDoom work over the internet? If not that is another good
reason to add Ultra Violence+ so people can experience the multiplayer things in maps. 

Example of this would be The Cyberdemon on MAP14 System Control in Final Doom. Fun times. :)

**Comment by BodbDearg** [comment]
Thanks for the suggestion! I gave this a try out via a quick and dirty hack. My thinking on it is that it doesn't add enough value versus the already existing Nightmare skill level to justify adding, since NM on the PSX already behaves much like UV+ minus all the extra weapons. Plus for technical reasons I want to avoid adding another skill level due to the implications that has for the password system.

Regarding network play there are no further additions or enhancements planned I'm afraid. Providing a really good MP experience would require a ton of changes that I feel go beyond the scope of the project. If you want to have a good multiplayer experience I think you're much better off looking at a source port focused on that, maybe with a PSX Doom mod loaded (e.g: https://zandronum.com/forum/viewtopic.php?t=2644) to get closer to the desired experience. The serial link mode in PSX Doom was kind of an afterthought by the developers and mainly present in PsyDoom for novelty purposes. For these reasons I don't devote a lot of time and energy towards it...
