### ISSUE TITLE
[Feature] Messages in widescreen

### ISSUE THREAD

**Issue by NightFright2k19** [BodbDearg/PsyDoom#59]
In widescreen, position of pickup messages remains the same as in 4:3 mode, i.e. not aligned to the left edge of the screen (on top of the statusbar). Same goes for map names in the automap. Would be nice to have this, either as an option or a plain feature.

**Comment by BodbDearg** [comment]
This is a pretty decent suggestion and sounds good in theory. I gave it a go however and it didn't feel very good... It's hard to describe but it almost felt distracting, like my eyes were constantly being drawn to the dead zone at the bottom left corner of the screen and away from the action.

I think this is why I didn't go for this idea initially, but I had forgotten the reasons :) If the status messages were at the top left of the screen (like Quake) I think it would be OK. Because the messages are so close to where the action is however left aligning definitely feels worse, and quite distracting.

**Comment by NightFright2k19** [comment]
I didn't consider that. It might indeed make a difference whether the messages are at the top of the screen or not. Guess I'll get used to the way it is, then. Thanks for thinking about it, anyway!
