### ISSUE TITLE
Android support? Maybe..


### ISSUE THREAD

**Issue by nerovingio** [BodbDearg/PsyDoom#6]
I would love to play it in my nvidiashield

**Comment by BodbDearg** [comment]
Hi @nerovingio thanks for checking out the project. I had considered the question of supporting iOS and Android previously and decided against it for a number of reasons. Those reasons stem mainly from a user experience standpoint (terrible touch-screen controls, more difficult to setup & configure etc.) but also due to distribution issues and the App Stores frowning upon reverse engineered works.

Windows, MacOS and Linux (eventually) will be the only officially supported platforms for PsyDoom.

Having that said the source is always there if someone feels strongly enough about porting, so who knows - maybe eventually someone will take this up. I don't consider it a worthwhile enough investment of my own time to pursue it however, sorry!
