### ISSUE TITLE
[Feature] Widescreen support for menu tiles

### ISSUE THREAD

**Issue by NightFright2k19** [BodbDearg/PsyDoom#60]
I tried to create widescreen replacements for some menu tiles (BACK and DEMON), but it appears PsyDoom would not center the images properly (leaves gaps on the left side).

What I tried:
- Resize one of the above mentioned images from 256x240 to 426x240 without offsets
- Apply a width offset of 85 (426-256 / 2) to the resized image

Ideally it could work like in GZDoom where such images are automatically centered, regardless of their width.

Note:
This is **NOT** about including widescreen assets for the port ([which had already been declined before](https://github.com/BodbDearg/PsyDoom/issues/26)), but rather adding mod support for it. While it may be impossible to provide consistent and complete widescreen support for all necessary graphics, I'd say if modders want to go for it anyway, let them.

**Comment by rrPKrr** [comment]
Hey!

Been testing the widescreen backgrounds and everything seems to be working fine except for the Title backgrounds. It takes `SCREEN_W` as a texture width which is 256 pixels. As a result if Title is wider than 256 pixels the function will draw only a part of the sprite (first 256 columns of pixels). So, instead of `SCREEN_W` it should be `gTex_TITLE.width`
https://github.com/BodbDearg/PsyDoom/blob/develop/game/Doom/UI/ti_main.cpp#L297
https://github.com/BodbDearg/PsyDoom/blob/develop/game/Doom/UI/ti_main.cpp#L372

**Comment by BodbDearg** [comment]
You're absolutely right, thanks for pointing out! I noticed this myself while working on an overhaul of the title screen code to support GEC ME Beta 4. I have changes in a private branch that add support for beta 4 which will also fix this issue; I'll be publishing those to the `develop` branch soon.

**Comment by BodbDearg** [comment]
Closing as implemented/fixed as of 1.1.0.
