### ISSUE TITLE
[Bug?] Automap zoom depends on Pan key

### ISSUE THREAD

**Issue by SoddenCub71** [BodbDearg/PsyDoom#66]
The "Controls" tab gives the impression that one can directly bind keys to zoom in and out on the automap.
![image](https://user-images.githubusercontent.com/114965480/197346381-e5077b70-dc94-49d1-8312-6b8557c12f89.png)
But in-game, the keys only function while the key assigned to "Pan" is held down.

**Comment by getphobo** [comment]
Personally, I do not mind the fact that an extra modifier button has to be pressed, although it would be better not to have to, but it is still a buggy feature because pressing the Pan button does not suppress any additional function on double-bound keys.

Example: I have set both weapon up/down and map zoom in/out to the mouse wheel. It should cycle through the weapons when the Pan button is not being pressed, and zoom in/out the automap when the Pan button is being pressed.

However, what is actually does is to cycle through the weapons in either case, but it will only zoom in/out the automap when the Pan button is also being pressed (and only if the automap is being shown, not in the game scene).

**Comment by SoddenCub71** [comment]
It looks like the behavior is consistent with the original game; assuming the manual is reliable.
![doompsx008](https://user-images.githubusercontent.com/114965480/198702240-d431f78f-a3c9-4b39-82b4-28264e5d496f.jpg)
"You can zoom in and out by holding the X Button and simultaneously pressing L1 (IN) or L2 (OUT)". But the launcher doesn't make that clear.

**Comment by fenderc01** [comment]
It's not exactly like that. It's actually hold X and use L1 and R1 (strafe left and right), but same idea.

My thought on this is this: I believe it should behave more like PC Doom and have a toggle (F for follow mode) instead of holding down a button to move the map around. The zoom keys should work all the time, as long as they're not assigned to another function. I think this would eliminate a lot of confusion. I've watched a few YouTube videos now where the person doesn't know how to zoom in and out or move the map around.

**Comment by SoddenCub71** [comment]
Anecdotally, I got pretty confused the first time I accidentally pressed the key for follow mode, and didn't know how to turn it off.

**Comment by NightFright2k19** [comment]
It's also like this in the Doom 64 Remaster, so I'd call this consistent. It's a "console thing".

**Comment by SoddenCub71** [comment]
The launcher interface could be clearer, in that case. Something like "Zoom in (when Pan held)"; or a separate section for "When Pan button is held".

**Comment by getphobo** [comment]
Still needs a fix regarding that mouse wheel zoom, no matter how the Pan key will be handled in the end.

**Comment by BodbDearg** [comment]
> Still needs a fix regarding that mouse wheel zoom, no matter how the Pan key will be handled in the end.

This issue will be fixed in the next release (see commit: 622b946d90722bfc74a589674539dfad60ac3e9d). You can no longer switch weapons while zooming in and out on the map. I also tweaked the Launcher messaging slightly to clarify that zoom in/out is only active while panning.

**Comment by BodbDearg** [comment]
Fixed the above issue as of 1.1.0 - closing ticket.
