### ISSUE TITLE
Failed to create a Vulkan texture for PSX VRAM

### ISSUE THREAD

**Issue by fenderc01** [BodbDearg/PsyDoom#8]
![error](https://user-images.githubusercontent.com/43886159/110337487-f8a0cb80-7ff3-11eb-9cd6-4e93a1485138.png)

First of all, this may just be an issue with my specific hardware. I have 2 other computers that I don't get the error message on and Vulkan works just fine.

When starting PsyDoom, I get the error message: "A fatal error has occurred! Failed to create a Vulkan texture for PSX VRAM!" This started happening after updating my video driver to the latest 2021 driver. Before updating my driver (2015), PsyDoom would start up with the classic renderer and not allow me to change to Vulkan, so it may just be that my video card doesn't support Vulkan.

My video card is the AMD Radeon HD 8790M. If this is just an issue due to incompatibility, feel free to close this issue.

**Comment by BodbDearg** [comment]
Thanks for reporting this issue! I suspect the problem might be that the 8790M driver only supports Vulkan 1.0; the only hardware database entry I see for that GPU references an 1.0.x API version: https://vulkan.gpuinfo.org/displayreport.php?id=1189

PsyDoom relies on a few features which are only found in Vulkan 1.1+. When you updated your driver it might have been that you went from a driver without Vulkan support to one that supports Vulkan 1.0, and because of this the game started trying to output via Vulkan and ran into this issue.

I've tightened up some of the device suitability checks in 8cf6315de4d036d495fca58da963f6a54e855a4b. I think if you try it again you might find that the Vulkan renderer will be unfortunately be off limits with that GPU, which will be the expected behavior if it doesn't meet the minimum requirements. In this case the game should fallback to using the old PSX renderer and use the OpenGL (via SDL) to blit the PSX framebuffer onto the Window.

I'm going to close the issue pre-emptively but feel free to re-open if this does not fix the error on that device.

**Comment by fenderc01** [comment]
Thanks for looking into this! Unfortunately, the error still comes up on the system in question.

**Comment by BodbDearg** [comment]
Oh dear... Thanks for checking the fix!

So in that case the 8790M driver must be reporting itself as Vulkan 1.1+ compliant, and it must be reporting that the texture format for PSX VRAM is supported and that it supports all the required format features. In this case I'm not really sure why it's failing to create the texture... It can't be memory because at that point I've already allocated a large chunk (64 MiB) from the GPU and the VRAM texture would use only a small part of that chunk (1 MiB). The sub allocation within the larger chunk is also controlled on the application side by PsyDoom and works the same for all GPUs, and should be deterministic.

At this point I'm kind of suspecting a driver issue (claiming to support texture formats it actually doesn't) but will check over the code again to see if there is anything I missed. Perhaps one way to workaround might be to do a test/dummy allocation of this texture type when initially checking for Vulkan support since it appears the driver can't be trusted to report it's capabilities 100% correctly.

**Comment by BodbDearg** [comment]
Just implemented the workaround mentioned above in 2e1088fbcadef2f4ec812db00618c7a3a9b21236. Hopefully this will at least let the game launch now with that card.

**Comment by fenderc01** [comment]
You fixed it! Thank you!

**Comment by BodbDearg** [comment]
Awesome, thanks for confirming @fenderc01 and for working through this issue with me!
