### ISSUE TITLE
Game minimizes when switching tasks (Windows 11)

### ISSUE THREAD

**Issue by SoddenCub71** [BodbDearg/PsyDoom#90]
I have two displays. I'd like to be able to keep the game open in one while doing things in the other. But currently, as soon as I use alt-tab to switch to something on the second screen, the game disappears from the first.

**Comment by BodbDearg** [comment]
Huh... that's an interesting one - thanks for pointing out. I see it happening on Windows 10 too, might be possibly something to do with the fullscreen exclusive mode.

**Comment by BodbDearg** [comment]
Confirmed that the game doesn't minimize when the Fullscreen mode is 'windowed borderless' instead of true/exclusive fullscreen. I think PsyDoom needs an option for the fullscreen mode (windowed vs exclusive) - at the minute it is always fully exclusive.

Note: there's already an option for whether the game pauses when it loses focus (under the 'Game' tab) but obviously that won't be of any use to you until the fullscreen mode option implemented. Those two things together should cover this ticket.

**Comment by BodbDearg** [comment]
Windowed borderless fullscreen mode is now available in [1.1.1](https://github.com/BodbDearg/PsyDoom/releases/tag/releases%2F1.1.1) and is the new default fullscreen mode. Combining this with the right setting for the 'pause on focus lost' option should allow you to achieve the desired behavior. Closing out ticket.
